# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Express JSON:API Controller
author: theParadoxicalWizard
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
#root: /

# Writing
relative_link: false

source_dir: docs

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../node_modules/hexo-theme-doc

theme_config:
  favicon: ../docs/images/favicon.ico


